In [2]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier as knc 

In [3]:
#enter the path to the train data
path = ''

In [8]:
train_data = pd.read_csv(path, index_col = ['id'])

In [9]:
train_data

X   Y  Class
id               
1   22  86      0
2   78  32      1
3   54  50      1
4   68  80      0
5   18  12      0
6   85  48      0
7   78  10      0
8   50  74      0
9   30  95      0
10  91  12      0

In [20]:
x_train = pd.DataFrame(train_data[['X', 'Y']])
y_train = train_data['Class']

In [16]:
#assign classificators (_ev - euclidean, _man - manhattan distance)
clf_ev = knc(n_neighbors = 3, p = 2)
clf_man = knc(n_neighbors = 3, p = 1)

In [33]:
#train models
clf_ev.fit(x_train, y_train)
clf_man.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3, p=1)

In [24]:
#enter your data from the task
new_obj = np.array([30,30])
new_obj = new_obj.reshape(1,2)
data_test= pd.DataFrame(new_obj, columns = ['X', 'Y'])

In [25]:
data_test

X   Y
0  30  30

In [38]:
#the first array - distances, the second one - th id of ellements in train_data (starting from 0)
clf_ev.kneighbors(data_test)

(array([[21.63330765, 31.2409987 , 48.0416486 ]]), array([[4, 2, 1]]))

In [35]:
#class of the element
clf_ev.predict(data_test)

0
0  1

In [34]:
#the first array - distances, the second one - th id of ellements in train_data (starting from 0)
clf_man.kneighbors(data_test)

(array([[30., 44., 50.]]), array([[4, 2, 1]]))

In [39]:
#class of the element
clf_man.predict(data_test)

array([1])